### ISSUE TITLE
Pause by default to allow Console.WriteLines to be seen

### ISSUE THREAD

**Issue by jkendall327** [lechu445/ConsoleMenu#11]
First off, really nice library - just the level of complexity I want.

This isn't a bug so much as behaviour that felt unintuitive to me. The first thing I did was set up a menu action to print something with `Console.WriteLine`.

```cs
        var menu = new ConsoleMenu();

        menu.Add("test", () => Console.WriteLine("hello world"));

        menu.Show();
```

I was surprised when selecting this option seemed to do nothing! My first thought was the menus somehow took over stdout, so I had to close and re-show the menus when I wanted to print something. After looking at the example app for a bit, I figured out the real reason - without a `Console.ReadKey()`, it loops back around to the menu too quickly for whatever your action might have printed out to be visible.

Given that 90% of what I might want to do is some variation on printing text, I think it would be useful to have a toggle in the `Configure()` method that automatically inserts a `ReadKey` after the supplied `Action` has finished executing, maybe with some optional 'press any key' text.

Cheers!

**Comment by lechu445** [comment]
hi @jkendall327!

I like your feature suggestion. It will ease usage the menu in simple scenarios. And, I think it's not very hard to implement it. Maybe you would like to create pull request with the change? :)

**Comment by jkendall327** [comment]
Sure, I'll take a look through the code this weekend and see if I can get something working :)

**Comment by lechu445** [comment]
@jkendall327 why did you close the issue?

**Comment by eXpl0it3r** [comment]
This becomes, to my knowledge, an unsolvable issue, if you have sub-menus. As your current menu items, don't know about the parent menu, so you can't close the whole hierarchy just to write something to the console.

The current implementation is quite limiting, as it seems like a common use case to mix menu selection with additional, non-menu user input and output, e.g. requesting someone to enter their name.

Am I missing something or is there no way to easily mix custom `Console.*` calls with ConsoleMenu?
