### ISSUE TITLE
Close menu and update menu item improvements

### ISSUE THREAD

**Issue by sfrippiat** [lechu445/ConsoleMenu#2]
Hello.

I used your library to write a quick console application. However I found 2 limitations:
- I did not find a way to close a menu except by creating a menu item with the ConsoleMenu.Close action attached. I had a case where I needed the user to select something in a list. The menu is the list of available options and when the user "opens" one of the menu, it allows me to get the selected item. I needed that action to close the menu instead of forcing the user to select a menu item and then closing it manually through an additional menu item.
- As the user selected something in a submenu, I needed a way to refresh a menu item. The menu item text had some text that depended on a selected value. When the user opens that menu item, it can select another value throught another menu. When that menu was closed I needed to update the current menu.

You'll find a patch for those modifications.
[ConsoleMenu.cs.patch.txt](https://github.com/lechu445/ConsoleMenu/files/3514914/ConsoleMenu.cs.patch.txt)

**Comment by lechu445** [comment]
Hi,
Thanks for reporting these issues. 
I will use your suggestion to prepare a new version that meets your needs.

**Comment by lechu445** [comment]
I deployed version 2.3.1. It has some changes in compare to your suggestion but I think you won't have a problem to update to newest version.
Basically change:
```csharp
menu.SetMenuItemName(menu.CurrentItem, "some name")
```
to
```csharp
menu.CurrentItem.Name = "some name";
```
and change from:
```csharp
menu.CloseMenu = true;
```
to
```csharp
menu.CloseMenu();
```

**Comment by sfrippiat** [comment]
Thanks a lot for the quick follow-up and new release. I had indeed no problem to update to the newest version.

Thanks !
