### ISSUE TITLE
Adding a user wait flag

### ISSUE THREAD

**Issue by osipud** [lechu445/ConsoleMenu#24]
Hi!

Is it possible to add a flag that will allow adding a wait for user action to some "Actions"?

I think I'll display the parameters for this action like this:
```
var menu = new ConsoleMenu(args, level: 0)
  .Add("One", () => SomeAction("One"),true)
  .Add("Two", () => SomeAction("Two"))
  .Add("Three", () => SomeAction("Three"))
  .Add("Change me", (thisMenu) => thisMenu.CurrentItem.Name = "I am changed!")
  .Add("Close", ConsoleMenu.Close)
  .Add("Action then Close", (thisMenu) => { SomeAction("Close"); thisMenu.CloseMenu(); })
  .Add("Exit", () => Environment.Exit(0))
  .Configure(config =>
  {
      config.MessageWaitingUserAction = "Press any key to continue...";
  });

menu.Show();
```

Here a true/false flag has been added to understand whether to wait for an action from the user.
`.Add("One", () => SomeAction("One"),true)`

And here is the message itself, which will be displayed after the end of the "Action"
```
  .Configure(config =>
  {
      config.MessageWaitingUserAction = "Press any key to continue...";
  });
```

**Comment by lechu445** [comment]
Hi @osipud!

You can already have the same behavior by adding `Console.WriteLine("Press any key to continue...")` into the last line of the action you are calling.

**Comment by osipud** [comment]
And tell me what to do with closed libraries, where there is no possibility to add such a command. It is not convenient to make an additional method for calling methods of someone else's library?

**Comment by osipud** [comment]
Added another method that takes an additional parameter

To solve this problem temporarily, I did this:

```
  public ConsoleMenu Add(string name, Action action, bool waitUser)
  {
    if (name == null)
    {
      throw new ArgumentNullException(nameof(name));
    }

    if (action == null)
    {
      throw new ArgumentNullException(nameof(action));
    }

    if (action.Target is ConsoleMenu child && action == child.Show)
    {
      child.parent = this;
    }

    this.menuItems.Add(name, (_) =>
    {
      if (waitUser)
      {
        this.Console.Clear();
        action();
        this.Console.WriteLine(this.config.MessageWaitingUserAction);
        this.Console.ReadKey();
        return Task.CompletedTask;
      }
      else
      {
        action();
        return Task.CompletedTask;
      }
    });
    return this;
  }
```

But a problem arose when the message about the completion of the method appears before the asynchronous method passed to Action ends.

**Comment by lechu445** [comment]
> And tell me what to do with closed libraries, where there is no possibility to add such a command. It is not convenient to make an additional method for calling methods of someone else's library?

You can wrap the method from closed library with your own wrapping method.

Example:
```c#
public void MyWrappingMethod()
{
  ExternalLibrary.SomeAction();
  Console.WriteLine("Press any key to continue...");
}
```
then just call the wrapping method
```c#
var menu = new ConsoleMenu(args, level: 0)
  .Add("One", () => MyWrappingMethod()));
menu.Show();
```

**Comment by osipud** [comment]
Good afternoon!

Did I understand correctly that changes to this proposal will not be made in future versions?

**Comment by lechu445** [comment]
I cannot guarantee that it will never be implemented. I am going to close this issue, but if the community would show demand in the future, it will be re-opened.

I understand that you wish this feature in the library, so you might not use any workarounds. Implementation of features always introduces a risk of new bugs, therefore I'd like to pick only these that there is a real need.
