### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by sclarke81** [lechu445/ConsoleMenu#3]
Hi,

This looks like a really interesting project and I'd like to make use of it, but before I do, could I check what license you've released it under? Would you be able to add a license file to the repo?

Thanks,

Stephen

**Comment by lechu445** [comment]
Hi!
Thank you. Glad to hear that! That is great idea to add license. Therefore I just added MIT license to the repo. Maybe this will make more people contribute to this project.
