### ISSUE TITLE
Menu titles and breadcrumbs

### ISSUE THREAD

**Issue by sclarke81** [lechu445/ConsoleMenu#4]
Would you be interested in adding support for titles and breadcrumbs? This would be so that you give each menu a title which is displayed at the top. As you drill down into lower level menus you'd get breadcrumbs to show you the menu structure that you're in e.g.

Main Menu -> Submenu 1 -> Submenu 2

I know that the heading can currently be modified, but I think it'd be nice to have baked in support for this.

**Comment by lechu445** [comment]
Yeah, that's good idea but current architecture is not good for this change because submenu actually don't know anything about parent menu.
I must figure out if this change can be made without breaking changes.

**Comment by sclarke81** [comment]
I was thinking about this earlier. It's not a well developed thought as I haven't had a chance to look at the code yet. How about adding a AddSubmenu method that takes a ConsoleMenu as an argument? There'd be no need to take a name as the menu item would use the submenu name. You could add a field to ConsoleMenu to store the parent and set this inside the AddSubmenu method. Then to get the title for any menu you walk the tree of parents.

**Comment by lechu445** [comment]
Hi, I just deployed version 2.4.0 that allows to write titles and breadcrumbs.
Here is config of these features:
```csharp
config.Title = "Main menu";
config.EnableWriteTitle = true;
config.EnableBreadcrumb = true;
config.WriteBreadcrumbAction = titles => Console.WriteLine(string.Join(" / ", titles));
```
Any feedback is welcome.

**Comment by jogotcha** [comment]
Hi, for me the Breadcrumbs always show the default Title(s) "My menu".
Am I doing something wrong? Any tips?

**Comment by lechu445** [comment]
Hi @jogotcha, could you provide code to reproduce the issue?

**Comment by jogotcha** [comment]
I just used the first sample from the [readme](https://github.com/lechu445/ConsoleMenu/blob/master/README.md)

and my output looks like this:
_My menu / My menu
Pick an option:
--> [0] Sub_One
    [1] Sub_Two
    [2] Sub_Three
    [3] Sub_Four
    [4] Sub_Close
Filter:_
