### ISSUE TITLE
Issue with running app from console with pre-selected menu items

### ISSUE THREAD

**Issue by olgazmi** [lechu445/ConsoleMenu#6]
There is an issue with running app from console with pre-selected menu items, when there are more menu levels set up than requested item depth.
If levels 0,1,2 are configured, using  --menu-select=0.1 results in  IndexOutOfRangeException

locally fixed ConsoleMenu.cs line:106
    //   if (level <= items.Count)
      if (level < items.Count)

**Comment by lechu445** [comment]
@olgazmi thank you for the report of this issue.

I have released a fix in version 2.4.2
