### ISSUE TITLE
Reentry into submenu does not work

### ISSUE THREAD

**Issue by gverbake** [lechu445/ConsoleMenu#7]
In demo program, choose submenu, then submenu close, then submenu again...
You cannot get a second time in the menu
(probaby the close bool is not un-set)

Nice & clean little library for the rest!

**Comment by lechu445** [comment]
@gverbake thanks for the nice words 😊
I can confirm and reproduce the issue. I will fix it in spare time.

**Comment by lechu445** [comment]
@gverbake I have just released https://www.nuget.org/packages/ConsoleMenu-simple/2.4.3 with fix for this issue.
Thanks once again for reporting it!
