### ISSUE TITLE
Implement IEnumerable to allow collection initializer in ConsoleMenu.

### ISSUE THREAD

**Issue by Epicguru** [lechu445/ConsoleMenu#8]
Hi,
If you implement the _IEnumerable_ interface in the `ConsoleMenu` class, it will allow users to use [collection initializers](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers) with no other changes required.

It is already possible to achieve this behavior by making a class that inherits from `ConsoleMenu` and implementing the interface:
``` C#
class MyConsoleMenu : ConsoleMenu, IEnumerable
{
    public IEnumerator GetEnumerator() => Items.GetEnumerator();        
}
```
This then allows me to use the collection initializer syntax, which I think looks way cleaner than chained methods:
``` C#
var menu = new MyConsoleMenu()
{
    {
        "Some option",
        () => { Log("You selected some option"); }
    },
    {
        "Close menu",
        menu => { Log("Closing the menu..."); menu.CloseMenu(); }
    },
};
menu.Show();
```

The reason why this works is because a collection initializer requires the following:
1. That the class implements the `IEnumerable` interface.
2. That the class has 1 or more public method with the name `Add` that have parameters.

The second condition is already met, so all we need is the interface. The actual `GetEnumerator()` is not actually used in the collection initializer constructor, but it still needs to be implemented (for reasons relating to ancient versions of .NET). Returning the items in the menu seems like the logical implementation.

I hope that this small change could be added to the ConsoleMenu class. It provides a nice syntax for those who want it and it does not affect any existing menus or uses.

**Comment by lechu445** [comment]
@Epicguru good idea, the dictionary-like initializer will be a clean & easy way to create the menu.

Would you like to create the PR that adds `GetEnumerator()`? It seems it's an easy task to do.

**Comment by Epicguru** [comment]
Will do.

**Comment by Epicguru** [comment]
Closing in favour of pull request #9.
